version: '3.8'
services:
  frontend:
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - midnat-dev-network
networks:
  midnat-dev-network:
    name: midnat-dev-network
    driver: bridge
